AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CoworkingSpacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: CoworkingSpaces
      Policies:
        - DynamoDBCrudPolicy:
            TableName: CoworkingSpaces
        - DynamoDBCrudPolicy:
            TableName: users
      Events:
        CoworkingSpacesApi:
          Type: Api
          Properties:
            Path: /spaces
            Method: any
        CoworkingSpacesProxy:
          Type: Api
          Properties:
            Path: /spaces/{proxy+}
            Method: any
        UsersProxy:
          Type: Api
          Properties:
            Path: /users/{proxy+}
            Method: any

  ReservationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: reservations.reservations.add_reservation  #